### ISSUE TITLE
Books Reducers Initial State Undefined

### ISSUE THREAD

**Issue by aali87** [StephenGrider/ReduxSimpleStarter#106]
I just finished lecture 42. That's about implementing the container class. I'm getting an issue with passing the initial state where my books reducer is being passed an undefined state. From what I can understand, we're passing in a hard coded books object as the state. Can somebody help? I've been stuck on this for about two days now.

![capture](https://cloud.githubusercontent.com/assets/11963521/24720741/2095d844-1a0c-11e7-92d3-9a9cf2ef768c.PNG)

**Comment by roz0n** [comment]
Did you ever get this to work?

**Comment by aali87** [comment]
Yeah - Turned out it was a type and it was fixed when I started over again. Are you getting the same issue?

**Comment by MarinaCode** [comment]
Hi ! I get this error 
![image](https://user-images.githubusercontent.com/17899184/28029240-731dc870-65b0-11e7-8a15-fe6f69d5fdd2.png)

I got it after 43  lesson. Can you help me , please

**Comment by 1andee** [comment]
Make sure the first argument you pass on Line 1 of reducer_active_book.js contains `state = null`.

Like so:
```
export default function(state = null, action) {
  switch(action.type) {
    case 'BOOK_SELECTED':
      return action.payload;
  }

  return state;
}
```

**Comment by jack1012t** [comment]
I am doing exactly as @1andee says, yet I still get this error: 

```
export default function(state = null, action) {
  switch(action.type) {
    case 'BOOK_SELECTED':
      return action.payload;
  }

  return state;
}
```
